In [7]:
#installing numpy library
! pip install numpy

In [3]:
# importing numpy as np
import numpy as np

In [4]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [5]:
%timeit [i**2 for i in  lst]

2.69 µs ± 50.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
arr = np.array(lst)

In [7]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
%timeit arr**2

565 ns ± 33.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
# if i want to add 1 to each element of this vector
lst + [1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [11]:
# but it's possible in numpy array
arr + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Numpy Basics

In [12]:
l = [1,5,8,9]

np_arr = np.array(l)

In [13]:
np_arr

array([1, 5, 8, 9])

In [14]:
type(np_arr)

numpy.ndarray

In [15]:
np_arr.ndim

1

In [16]:
# Important
np_arr.shape

(4,)

In [17]:
# Another way way of creating np array

new_arr = np.arange(3,11,2)

In [18]:
new_arr

array([3, 5, 7, 9])

In [19]:
lst_2nd = [[1,2,3], [4,5,6], [7,8,9]]

In [20]:
arr_2d = np.array(lst_2nd)

In [21]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr_2d.shape

(3, 3)

In [23]:
arr_2d.ndim

2

#Special Arrays in Numpy

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [27]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#Indexing in Array

In [28]:
np.random.randint(10,100)

42

In [29]:
new_arr = np.random.randint(0, 20, (5,4))

In [30]:
new_arr

array([[15, 13, 16, 18],
       [ 3, 14,  4,  5],
       [12,  7,  8,  8],
       [ 5,  1, 18,  2],
       [10, 11, 16,  0]])

In [31]:
new_arr.shape

(5, 4)

In [32]:
# first row
new_arr[0]

array([15, 13, 16, 18])

In [59]:
#second last row
new_arr[-2]

array([4, 4, 0, 9])

In [60]:
#first element
print(new_arr[0,0])

# last element
print(new_arr[4, 3])

13
5


#Array slicing

In [62]:
new_arr

array([[13, 19, 11, 13],
       [ 6,  2, 16,  4],
       [ 7,  3, 13,  6],
       [ 4,  4,  0,  9],
       [ 3,  0,  9,  5]])

In [64]:
# arr[start_row_idx : end_row_idx +1, start_col_idx : end_col_idx + 1]

In [65]:
new_arr [2 : , 1:,]

array([[ 3, 13,  6],
       [ 4,  0,  9],
       [ 0,  9,  5]])

In [72]:
#for column
new_arr[ : , 1]

array([19,  2,  3,  4,  0])

In [78]:
new_arr[0,0] = 0

In [80]:
new_arr

array([[ 0, 19, 11, 13],
       [ 6,  2, 16,  0],
       [ 7,  3, 13,  6],
       [ 4,  4,  0,  9],
       [ 3,  0,  9,  5]])

In [87]:
#masking
mask = new_arr > 10
print(mask)

[[False  True  True  True]
 [False False  True False]
 [False False  True False]
 [False False False False]
 [False False False False]]


In [88]:
np.sum(mask)

5

In [89]:
#get all values greater than 10
new_arr[mask]

array([19, 11, 13, 16, 13])

In [90]:
new_arr

array([[ 0, 19, 11, 13],
       [ 6,  2, 16,  0],
       [ 7,  3, 13,  6],
       [ 4,  4,  0,  9],
       [ 3,  0,  9,  5]])

In [91]:
new_arr[2:, 2:] = 0

In [92]:
new_arr

array([[ 0, 19, 11, 13],
       [ 6,  2, 16,  0],
       [ 7,  3,  0,  0],
       [ 4,  4,  0,  0],
       [ 3,  0,  0,  0]])

#Basic operations in Arrays

In [93]:
a = np.array([10,20,30,40])
b = np.arange(1,5)

In [94]:
a

array([10, 20, 30, 40])

In [95]:
b

array([1, 2, 3, 4])

In [96]:
a + b

array([11, 22, 33, 44])

In [97]:
a - b

array([ 9, 18, 27, 36])

In [99]:
a * b

array([ 10,  40,  90, 160])

In [100]:
b**2

array([ 1,  4,  9, 16])

In [101]:
#masking
a > 2

array([ True,  True,  True,  True])

In [103]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [104]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [114]:
#matrix dot product
A = np.random.randint(0,5,(3,4))
B = np.random.randint(0,5,(4,2))

In [115]:
A

array([[3, 0, 0, 1],
       [2, 3, 2, 2],
       [2, 1, 2, 0]])

In [116]:
B

array([[4, 3],
       [4, 0],
       [1, 3],
       [4, 1]])

In [117]:
#Dot product
np.dot (A,B)

array([[16, 10],
       [30, 14],
       [14, 12]])

In [118]:
A = np.arange(0,24)

In [119]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [120]:
A = A.reshape(6,4)

In [121]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [122]:
np.sqrt(A)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [123]:
np.sum(A)

276

In [124]:
np.max(A)

23

In [125]:
np.mean(A)

11.5

In [126]:
np.std(A)

6.922186552431729

In [127]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [128]:
np.sum(A, axis=0)

array([60, 66, 72, 78])

In [132]:
np.mean(A, axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5, 21.5])

In [130]:
np.sum(A, axis=1)

array([ 6, 22, 38, 54, 70, 86])

#Shape Manupulation

In [135]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [136]:
A.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [137]:
A.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [138]:
A.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [139]:
np.transpose(A)

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

#Stacking of arrays

In [145]:

a = np.random.randint(0,10,(2,2))
b = np.random.randint(0,10,(2,2))


In [146]:
a

array([[2, 5],
       [1, 2]])

In [147]:
b

array([[1, 8],
       [0, 5]])

In [148]:
np.hstack((a,b))

array([[2, 5, 1, 8],
       [1, 2, 0, 5]])

In [149]:
np.vstack((a,b))

array([[2, 5],
       [1, 2],
       [1, 8],
       [0, 5]])

#Broadcasting

In [168]:
A = np.random.randint(0, 10, size =(3,3))
a=np.array([[1,2,3]])

In [169]:
A

array([[2, 5, 7],
       [5, 2, 2],
       [9, 4, 3]])

In [170]:
a

array([[1, 2, 3]])

In [171]:
A + a

array([[ 3,  7, 10],
       [ 6,  4,  5],
       [10,  6,  6]])

In [172]:
a.T

array([[1],
       [2],
       [3]])

In [175]:
A + a.T

array([[ 3,  6,  8],
       [ 7,  4,  4],
       [12,  7,  6]])

In [176]:
A

array([[2, 5, 7],
       [5, 2, 2],
       [9, 4, 3]])

In [177]:
A +4

array([[ 6,  9, 11],
       [ 9,  6,  6],
       [13,  8,  7]])

#Vectorization

In [187]:
p1 = np.array([1,2,4,5,7,8,9,2])
p2 = np.array([5,5,4,6,8,9,2,4])

In [188]:
s=0
for i in range (8):
    s+= (p2[i] - p1[i])**2

In [189]:
s**0.5

9.0

In [190]:
#efficient
np.sqrt(np.sum ((p2-p1)**2))

9.0

In [191]:
def distance (p1,p2):
    return(np.sqrt(np.sum ((p2-p1)**2)))

In [192]:
distance(p1, p2)

9.0